### ISSUE TITLE
Crash on start-up; Obfuscation Reflection gone bad...

### ISSUE THREAD

**Issue by mgrouse** [MysticMods/MysticalLib#27]
Hello: 

The lib crashes the game on start-up even w/o the mod I wanted to use that requires it in the mod folder.

Ping me if you have any more questions.

Thanks

[crash-2019-10-14_18.31.30-client.txt](https://github.com/MysticMods/MysticalLib/files/3727043/crash-2019-10-14_18.31.30-client.txt)

**Comment by noobanidus** [comment]
Mystical Lib requires 2847 or higher, you're using Forge 2768, which is a year and a half old.

**Comment by mgrouse** [comment]
> Mystical Lib requires 2847 or higher, you're using Forge 2768, which is a year and a half old.

Ooooops! Sorry. After updating and a little forge wrangling everything now works perfectly!

Thanks for your parts in making Minecraft even more fun!

Michael

**Comment by noobanidus** [comment]
No worries! 2847 gives so many amazing advancements including the ability to selectively determine how hydration works, meaning that I can improve the Sure-Footed Stone to no longer have bugs like... "oh you can pick it up with a bucket and it turns into a bucket of water". 

Glad you got it working, and thank you for reporting it -- there was every chance that the issue was actually one of ours, and the initiative in coming here & filing something makes me so happy because I know there's one more person who's actually willing to *report* bugs when they happen. <3
