### ISSUE TITLE
Crashing during loading with NetherEX installed & Turned on

### ISSUE THREAD

**Issue by Tyinor** [MysticMods/MysticalLib#28]
I'm currently crashing with MysticalLib being identified as the potential subject with the installation of NetherEX. If I turn NetherEX off it loads fine: I have tried backdating my Roots, NetherEX & MysticalLib to older release versions as far back as their previous three versions. Four for NetherEX since they updated again today & It's still facing the same problem, I've not tried any versions earlier than September 5th to see exactly where it started as one of the Authors commented it worked in the past. 

https://pastebin.com/WrHX8VdR

**Comment by noobanidus** [comment]
Your issue here is unfortunately that you've run out of blocks, most likely because Mystical World added a few blocks and you were very close to the limit. This is a very complex issue to solve: 

a) make sure you always have a good back-up of the world
b) you can install something like Just Enough IDs to increase the block limit past 4096 -- but this can cause issues when removing or adding mods (although it is MORE stable with this than Not Enough IDs)
c) VERY DANGEROUS, DO A BACK-UP FIRST: if you have removed mods in the past, you can use NBT Explorer to go into the `level.dat` and find the `minecraft:blocks` or `forge:blocks` (I forget which) registry and find block entries from those mods, right click and delete them.

As Forge specifically keeps removed blocks registered in case you want to restore them, even removing a mod *after* it has added blocks will not reduce the number of block IDs that you are using.

Thankfully, this limitation of 4096 blocks is removed in 1.13+. Unfortunately, while Mystical World is partially available for 1.14.4, I've yet to begin porting Roots. 

Good luck, and if you need any help in resolving this please feel free to reply here or message me directly ("nooby" on Discord) on the Mystic Mods discord. I'm usually available between 8am-11pm AEST.

**Comment by Tyinor** [comment]
I'll give this a shot later tonight & If it fixes the issue I'll close the issue :) 

I honestly wasn't aware the block ID limit was still in on 1.12.2, that's good information to have.

**Comment by noobanidus** [comment]
Yeah, `java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.` is referring precisely to the block registry.

**Comment by noobanidus** [comment]
Additionally, if the error is occurring when you launch the game, that means you have too many blocks -- if the error occurs when you're trying to enter your world, that means your world has blocks that can be culled.

**Comment by Tyinor** [comment]
Startup issue resolved.

I was able to load into the world to confirm that no further issues existed. 

I don't know why MysticalLib was singled out since I had installed NetherEx like 10 days after I'd already began playing, so It's not like this mod was the newest.. But I sincerely thank you for the time all the same in helping me resolve this issue. :)

**Comment by noobanidus** [comment]
This is because MysticalLib back-loads all of the block registration for both Roots and Mystical World, which have a fair chunk of blocks -- effectively they are registered in MysticalLib, later in the loading process. Thus, when it hits the error of "too many IDs", it's because everything else has filled up the IDs and now Roots & Mystical World are trying to add theirs.
