### ISSUE TITLE
"Minecraft failed to start!"

### ISSUE THREAD

**Issue by ZovaZey** [MysticMods/MysticalLib#29]
"The following mod(s) have been identified as the potential cause:"
https://paste.dimdev.org/tofixuciga.mccrash

**Comment by noobanidus** [comment]
Please have a look at issue #28, which is identical to yours. You have too many mods installed that add blocks. The reason Mystical Lib is mentioned is because it does the registering for Mystical World and Roots. 

You'll have to remove some other block-heavy mods or install something like Just Enough IDs, although that can have dangers/downsides.
