### ISSUE TITLE
what version of the mod is for forge 14.23.5.2838?

### ISSUE THREAD

**Issue by ghost** [MysticMods/MysticalLib#57]
i need to know because im using that version of forge specifically because im editing a modpack

**Comment by noobanidus** [comment]
Two questions:

1. What mod are you using that requires MysticalLib? The answer to this determines which versions you can use.

2. Alternately, can you try updating the modpack to use 2847? Unfortunately, we've been using 2847 since, at the very least, the original release of Roots 3 in 2019. As far as I'm aware, most of the mods that would run on 2838 should also run on 2847. 2847 is technically the canonical "final" version (although the "recommended release" is 2855, which it should also work with).

**Comment by noobanidus** [comment]
(Further on 1: If you're using Roots or Mystical World, you'll need the 2847 version of MysticalLib/the latest version of MysticalLib. If you are using another mod, however, which hasn't been updated recently, it might be possible to get away with an older version of MysticalLib.)

**Comment by ghost** [comment]
it turns out it is a mod called blockcraftery, and it will take any version.

**Comment by ghost** [comment]
im just gonna delete it. i dont remember getting blockcraftery. i dont want blockcraftery. thanks anyway though.

**Comment by ghost** [comment]
i reopened it because someone who actually wants the mod might somehow get this issue.

**Comment by noobanidus** [comment]
I'm closing it because most people should be able to use the latest version.
